package com.tepuytech.fitzon.domain.enums

enum class BoxNotificationType {
    NEW_MEMBER, PAYMENT_RECEIVED, PAYMENT_PENDING, COACH_AVAILABILITY, WOD_PUBLISHED,
    CLASS_RESERVATION, CLASS_CANCELLED, MEMBER_MESSAGE, REPORT, REVIEW, SYSTEM
}
